baseURL = "https://example.com"
languageCode = "en-us"
title = "jbenite2"
theme = "sourgough-starter"
relativeURLs = true
enableEmoji=true

[markup.goldmark.renderer]
    unsafe= true

[params]
#------------- Config -------------------
    scholarLink = true
    scopusLink = true
    dimensionsLink = true
    dimensionCitations = true
    backgroundPath = "images/SA_back.png"
    googleScholar = 'XXXX' # These are needed only if set to true above
    scopusID = 'XXXX'
    dimensionsID = 'XXXX'
    footerOffset = -60

#-------------- Defined ------------
    css= ["css/sourgough.css"]

[menu]
#----- Navbar links ------
  [[menu.main]]
    identifier = "Blog"
    name = "Blog"
    url = "/blog/"

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"

#----- NavBottom Links ------
  [[menu.bot]]
    identifier = "github"
    name = "Github"
    url = "https://github.com/jbenite2"
    pre = "fab fa-github"

  [[menu.bot]]
    identifier = "linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/jose-benitez-70bb1918a/"
    pre = "fab fa-linkedin-in"

  

#-------- About section links ----- 
  [[menu.about]]
    identifier = "ordcidid"
    name = "OrcidID"
    url = ""
    pre = "fab fa-orcid"

  [[menu.about]]
    identifier = "researchgate"
    name = "ResearchGate"
    url = ""
    pre = "fab fa-researchgate"

  [[menu.about]]
    identifier = "medium"
    name = "Medium"
    url = ""
    pre = "fab fa-medium-m"

  [[menu.about]]
    identifier = "googlescholar"
    name = "Google Scholar"
    url = ""
    pre = "fas fa-graduation-cap"

#----------- Text Links -------
  [[menu.link]]
    identifier = "email"
    name = "joselbenitez.pr@gmail.com"
    url = "mailto:joselbenitez.pr@gmail.com"

  [[menu.link]]
    identifier = "resume"
    name = "resume"
    url = ""

[taxonomies]
  authors = "authors"